# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-11 08:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experchat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expert',
            name='display_name',
            field=models.CharField(max_length=100, null=True, unique=True, verbose_name='display name'),
        ),
    ]
