# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-27 06:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('experchat', '0006_promocode'),
    ]

    operations = [
        migrations.CreateModel(
            name='FollowExpert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_timestamp', models.DateTimeField(auto_now_add=True, verbose_name='created timestamp')),
                ('expert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followers', to='experchat.Expert', verbose_name='expert')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following', to='experchat.User', verbose_name='user')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='followexpert',
            unique_together=set([('expert', 'user')]),
        ),
    ]
