# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-10 06:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('experchat', '0008_auto_20170505_0522'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='experchat.Tag'),
        ),
        migrations.AddField(
            model_name='tag',
            name='type',
            field=models.CharField(choices=[('child', 'CHILD'), ('parent', 'PARENT'), ('synonym', 'SYNONYM')], default='parent', max_length=50, verbose_name='type'),
        ),
    ]
