# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-10 08:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('experchat', '0009_expertprofile_is_featured'),
        ('experchat', '0009_auto_20170510_0644'),
    ]

    operations = [
    ]
