# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-12 09:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('experchat', '0010_merge_20170510_0805'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='type',
            new_name='tag_type',
        ),
    ]
