# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-16 06:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experchat', '0012_expertprofile_review_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='ecsession',
            name='promo_code',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='promo code'),
        ),
    ]
