# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-16 06:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experchat', '0013_ecsession_promo_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='promocode',
            name='user_usage_limit',
            field=models.PositiveIntegerField(default=1, verbose_name='user usage limit'),
        ),
    ]
