# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-18 09:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experchat', '0014_promocode_user_usage_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='expertprofile',
            name='profile_submission_timestamp',
            field=models.DateTimeField(null=True, verbose_name='profile submission datetime'),
        ),
    ]
