# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-27 09:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('experchat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('experchat.ecdevice',),
        ),
    ]
