# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-17 09:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
        ('experchat_sessions', '0002_custom_create_session_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_timestamp', models.DateTimeField(auto_now_add=True, verbose_name='created timestamp')),
                ('modified_timestamp', models.DateTimeField(auto_now=True, verbose_name='modified timestamp')),
                ('session_event_type', models.CharField(default='', max_length=50, verbose_name='session event type')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='experchat_sessions.Session', verbose_name='session')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payments.Transaction', verbose_name='transaction')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
