# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-01 09:00
from __future__ import unicode_literals

from django.db import migrations
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('experchat_sessions', '0003_sessiontransaction'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SessionEvent',
        ),
    ]
