# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-04 06:52
from __future__ import unicode_literals

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.0000'), max_digits=12),
        ),
    ]
