# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-16 06:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('experchat', '0008_auto_20170505_0522'),
        ('payments', '0002_auto_20170504_1222'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='promo_code',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='experchat.PromoCode', verbose_name='promo_code'),
        ),
    ]
