# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-22 09:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20170223_2046'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='modified_timestamp',
            field=models.DateTimeField(auto_now=True, verbose_name='modified timestamp'),
        ),
    ]
