# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-02 07:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('experchat', '0007_auto_20170427_0639'),
        ('feeds', '0002_auto_20170428_1129'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentUserActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_timestamp', models.DateTimeField(auto_now_add=True, verbose_name='created timestamp')),
                ('modified_timestamp', models.DateTimeField(auto_now=True, verbose_name='modified timestamp')),
                ('activity_type', models.CharField(choices=[('like', 'Like Content'), ('favorite', 'Save Content As Favorite')], max_length=16, verbose_name='activity type')),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_activity', to='feeds.Content', verbose_name='content')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity', to='experchat.User', verbose_name='user')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
