# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-15 11:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('experchat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyStats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_timestamp', models.DateTimeField(auto_now_add=True)),
                ('modified_timestamp', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(auto_now=True)),
                ('count', models.PositiveIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='TagStats',
            fields=[
                ('created_timestamp', models.DateTimeField(auto_now_add=True)),
                ('modified_timestamp', models.DateTimeField(auto_now=True)),
                ('tag', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='experchat.Tag')),
                ('total_search_count', models.PositiveIntegerField(default=0)),
                ('last_week_search_count', models.PositiveIntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='dailystats',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='experchat.Tag'),
        ),
        migrations.AlterUniqueTogether(
            name='dailystats',
            unique_together=set([('tag', 'date')]),
        ),
    ]
