# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-24 09:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0002_auto_20170215_1132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailystats',
            name='created_timestamp',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created timestamp'),
        ),
        migrations.AlterField(
            model_name='dailystats',
            name='modified_timestamp',
            field=models.DateTimeField(auto_now=True, verbose_name='modified timestamp'),
        ),
        migrations.AlterField(
            model_name='tagstats',
            name='created_timestamp',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created timestamp'),
        ),
        migrations.AlterField(
            model_name='tagstats',
            name='modified_timestamp',
            field=models.DateTimeField(auto_now=True, verbose_name='modified timestamp'),
        ),
    ]
