# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-15 10:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0003_auto_20170224_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailystats',
            name='count',
            field=models.PositiveIntegerField(default=1, verbose_name='Count'),
        ),
        migrations.AlterField(
            model_name='dailystats',
            name='date',
            field=models.DateField(auto_now=True, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='dailystats',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='experchat.Tag', verbose_name='Tag'),
        ),
        migrations.AlterField(
            model_name='tagstats',
            name='last_week_search_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Last Week Search'),
        ),
        migrations.AlterField(
            model_name='tagstats',
            name='tag',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, serialize=False, to='experchat.Tag', verbose_name='Tag'),
        ),
        migrations.AlterField(
            model_name='tagstats',
            name='total_search_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Total Search'),
        ),
    ]
