# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-17 14:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0004_auto_20170315_1010'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyExpertStats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_timestamp', models.DateTimeField(auto_now_add=True, verbose_name='created timestamp')),
                ('modified_timestamp', models.DateTimeField(auto_now=True, verbose_name='modified timestamp')),
                ('profile_visits', models.PositiveIntegerField(default=1, verbose_name='Profile Visits')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Date')),
                ('expert', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='daily_stats', to='experchat.Expert', verbose_name='expert')),
            ],
            options={
                'ordering': ('-date', 'expert'),
            },
        ),
    ]
