# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-20 13:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0006_auto_20170318_1130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tagstats',
            name='tag',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, related_name='stats', serialize=False, to='experchat.Tag', verbose_name='Tag'),
        ),
    ]
