# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-21 14:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0007_auto_20170320_1918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailystats',
            name='count',
            field=models.PositiveIntegerField(default=1, verbose_name='count'),
        ),
        migrations.AlterField(
            model_name='dailystats',
            name='date',
            field=models.DateField(auto_now=True, verbose_name='date'),
        ),
        migrations.AlterField(
            model_name='dailystats',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='experchat.Tag', verbose_name='tag'),
        ),
        migrations.AlterField(
            model_name='tagstats',
            name='last_week_search_count',
            field=models.PositiveIntegerField(default=0, verbose_name='last week search'),
        ),
        migrations.AlterField(
            model_name='tagstats',
            name='tag',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, related_name='stats', serialize=False, to='experchat.Tag', verbose_name='tag'),
        ),
        migrations.AlterField(
            model_name='tagstats',
            name='total_search_count',
            field=models.PositiveIntegerField(default=0, verbose_name='total search'),
        ),
    ]
