# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-06 20:48
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VerificationToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_timestamp', models.DateTimeField(auto_now_add=True, verbose_name='created timestamp')),
                ('modified_timestamp', models.DateTimeField(auto_now=True, verbose_name='modified timestamp')),
                ('token', models.CharField(blank=True, db_index=True, max_length=64, null=True, verbose_name='verification token')),
                ('purpose', models.PositiveSmallIntegerField(choices=[(1, 'Email Verification'), (2, 'Phone Verification'), (3, 'Password Reset')], db_index=True, verbose_name='purpose')),
                ('notify_count', models.PositiveSmallIntegerField(default=1, verbose_name='api hit count')),
                ('expired_at', models.DateTimeField(blank=True, null=True, verbose_name='expired at')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'ordering': ('-modified_timestamp',),
            },
        ),
    ]
