# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-18 11:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='message',
            field=models.TextField(default='Call Schedule: Migration Message for old version notifications.'),
            preserve_default=False,
        ),
    ]
